apiVersion: v1
kind: Service
metadata:
  name: lanchonete
  labels:
    run: lanchonete-soat7
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32712
  type: NodePort
  selector:
    app: lanchonete-soat7