version: "3"
services:
  db:
    image: "postgres:12"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  webapp:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
