version: "3"
services:
  db:
    image: "postgres:12"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  webapp:
    build: .
    restart: always
    environment:
      APP_ENV: ${APP_ENV}
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
