version: "3"
services:
  db:
    image: "postgres:12.18-alpine3.19"
    restart: always
    networks:
      - lanchonete
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
  webapp:
    build: .
    restart: always
    networks:
      - lanchonete
    environment:
      - APP_ENV=prod
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
networks:
  lanchonete:
    driver: bridge